Add calendar
js-tasks-ru/htmlcss-20220317_dieillusion pull request #10
Opened 2022-04-04 17:31 UTC by dieillusion

2022-04-04 17:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-05 14:43 UTC, GSemikozov requested changes

2022-04-05 14:43 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    font-weight: var(--font-weight-600);;
`;;` - синтаксическая ошибка)

2022-04-05 14:45 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-05 14:48 UTC, GSemikozov approved these changes

2022-04-05 14:48 UTC, merged